// src/constants/premiumAuthStyles.js
// Dark glass auth UI on top of PremiumScreenShell.

import { StyleSheet } from 'react-native';
import { FONT, SPACING, RADIUS, SHADOWS } from './theme';
import { PREMIUM } from './premiumScreenTheme';

export function createPremiumAuthStyles(C) {
  return StyleSheet.create({
    container: { flex: 1 },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: SPACING.lg,
      paddingBottom: SPACING.md,
    },
    backBtn: {
      width: 40,
      height: 40,
      borderRadius: RADIUS.md,
      backgroundColor: PREMIUM.backBtnBg,
      borderWidth: 1,
      borderColor: PREMIUM.glassBorder,
      alignItems: 'center',
      justifyContent: 'center',
    },
    logoBadge: {
      paddingHorizontal: SPACING.md,
      paddingVertical: SPACING.xs,
      backgroundColor: 'rgba(74,222,128,0.14)',
      borderRadius: RADIUS.full,
      borderWidth: 1,
      borderColor: 'rgba(74,222,128,0.28)',
    },
    logoBadgeText: { ...FONT.label, color: PREMIUM.accent },
    scroll: {
      paddingHorizontal: SPACING.xl,
      paddingTop: SPACING.xxl,
      paddingBottom: 40,
    },
    title: { ...FONT.h1, color: PREMIUM.text, marginBottom: SPACING.xs },
    subtitle: { ...FONT.body, color: PREMIUM.textMuted, marginBottom: SPACING.xxl },
    errorBanner: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: SPACING.sm,
      backgroundColor: 'rgba(254,226,226,0.95)',
      borderRadius: RADIUS.md,
      padding: SPACING.md,
      marginBottom: SPACING.lg,
    },
    errorText: { ...FONT.bodySmall, color: C.error, flex: 1 },
    form: { gap: SPACING.lg, marginBottom: SPACING.xxl },
    field: { gap: SPACING.sm },
    label: { ...FONT.label, color: PREMIUM.text },
    labelRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
    forgotText: { ...FONT.bodySmallMedium, color: PREMIUM.accent },
    inputWrap: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: PREMIUM.inputBg,
      borderRadius: RADIUS.xl,
      borderWidth: 1.5,
      borderColor: PREMIUM.glassBorder,
      paddingHorizontal: SPACING.md,
      height: 54,
    },
    inputWrapError: {
      borderColor: C.error,
      borderWidth: 2,
    },
    fieldError: { ...FONT.caption, color: C.error, marginTop: 4 },
    inputIcon: { marginRight: SPACING.sm },
    input: { flex: 1, ...FONT.body, color: PREMIUM.text },
    eyeBtn: { padding: SPACING.xs },
    primaryBtn: { borderRadius: RADIUS.lg, overflow: 'hidden', marginBottom: SPACING.xxl, ...SHADOWS.green },
    primaryBtnDisabled: { opacity: 0.7 },
    primaryBtnGradient: { height: 54, alignItems: 'center', justifyContent: 'center' },
    primaryBtnText: { ...FONT.h5, color: '#FFFFFF', fontWeight: '700' },
    divider: { flexDirection: 'row', alignItems: 'center', gap: SPACING.md, marginBottom: SPACING.lg },
    dividerLine: { flex: 1, height: 1, backgroundColor: PREMIUM.glassBorder },
    dividerText: { ...FONT.bodySmall, color: PREMIUM.textMuted },
    social: { flexDirection: 'row', justifyContent: 'center', gap: SPACING.md, marginBottom: SPACING.xxl },
    socialBtn: {
      width: 52,
      height: 52,
      borderRadius: RADIUS.md,
      backgroundColor: PREMIUM.inputBg,
      borderWidth: 1.5,
      borderColor: PREMIUM.glassBorder,
      alignItems: 'center',
      justifyContent: 'center',
    },
    socialBtnLabel: { ...FONT.h4, color: PREMIUM.text },
    footer: { alignItems: 'center' },
    footerText: { ...FONT.body, color: PREMIUM.textMuted },
    footerLink: { color: PREMIUM.accent, fontWeight: '600' },
    strength: { flexDirection: 'row', alignItems: 'center', gap: SPACING.sm, marginTop: SPACING.xs },
    strengthBar: { flex: 1, flexDirection: 'row', gap: 4 },
    strengthSegment: { flex: 1, height: 3, borderRadius: 2 },
    strengthLabel: { ...FONT.captionMedium },
    agreeRow: { flexDirection: 'row', alignItems: 'flex-start', gap: SPACING.sm },
    checkbox: {
      width: 20,
      height: 20,
      borderRadius: RADIUS.xs,
      borderWidth: 1.5,
      borderColor: PREMIUM.glassBorder,
      alignItems: 'center',
      justifyContent: 'center',
      marginTop: 1,
    },
    checkboxActive: { backgroundColor: '#22C55E', borderColor: '#22C55E' },
    agreeText: { ...FONT.bodySmall, color: PREMIUM.textMuted, flex: 1, lineHeight: 18 },
    agreeLink: { color: PREMIUM.accent, fontWeight: '600' },
  });
}

export function createPremiumForgotStyles(C) {
  return StyleSheet.create({
    container: { flex: 1 },
    header: { paddingHorizontal: SPACING.lg, paddingBottom: SPACING.md },
    backBtn: {
      width: 40,
      height: 40,
      borderRadius: RADIUS.md,
      backgroundColor: PREMIUM.backBtnBg,
      borderWidth: 1,
      borderColor: PREMIUM.glassBorder,
      alignItems: 'center',
      justifyContent: 'center',
    },
    content: { flex: 1, paddingHorizontal: SPACING.xl, paddingTop: SPACING.xxl },
    iconWrap: { marginBottom: SPACING.xxl },
    icon: {
      width: 72,
      height: 72,
      borderRadius: RADIUS.xl,
      alignItems: 'center',
      justifyContent: 'center',
    },
    title: { ...FONT.h1, color: PREMIUM.text, marginBottom: SPACING.sm },
    subtitle: { ...FONT.body, color: PREMIUM.textMuted, lineHeight: 24, marginBottom: SPACING.xxl },
    emailHighlight: { color: PREMIUM.accent, fontWeight: '600' },
    errorBanner: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: SPACING.sm,
      backgroundColor: 'rgba(254,226,226,0.95)',
      borderRadius: RADIUS.md,
      padding: SPACING.md,
      marginBottom: SPACING.lg,
    },
    errorText: { ...FONT.bodySmall, color: C.error, flex: 1 },
    field: { gap: SPACING.sm, marginBottom: SPACING.xxl },
    label: { ...FONT.label, color: PREMIUM.text },
    inputWrap: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: PREMIUM.inputBg,
      borderRadius: RADIUS.md,
      borderWidth: 1.5,
      borderColor: PREMIUM.glassBorder,
      paddingHorizontal: SPACING.md,
      height: 52,
    },
    inputIcon: { marginRight: SPACING.sm },
    input: { flex: 1, ...FONT.body, color: PREMIUM.text },
    sendBtn: { borderRadius: RADIUS.lg, overflow: 'hidden', marginBottom: SPACING.lg, ...SHADOWS.green },
    sendBtnGradient: { height: 54, alignItems: 'center', justifyContent: 'center' },
    sendBtnText: { ...FONT.h5, color: '#FFFFFF' },
    backToLogin: { alignItems: 'center', paddingVertical: SPACING.md },
    backToLoginText: { ...FONT.bodyMedium, color: PREMIUM.accent },
    successWrap: { alignItems: 'center', paddingTop: SPACING.section },
    successIcon: {
      width: 88,
      height: 88,
      borderRadius: RADIUS.xxl,
      backgroundColor: 'rgba(74,222,128,0.18)',
      borderWidth: 1,
      borderColor: 'rgba(74,222,128,0.35)',
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: SPACING.xxl,
    },
  });
}
