// src/constants/premiumAuthStyles.js
// Light cream auth UI — warm background, clean inputs, sage green accents.

import { StyleSheet } from 'react-native';
import { FONT, SPACING, RADIUS, SHADOWS } from './theme';

const LIGHT = {
  bg:           'transparent',
  surface:      'rgba(255, 255, 255, 0.55)',
  text:         '#0D3B26',
  textMuted:    'rgba(13, 59, 38, 0.6)',
  textHint:     'rgba(13, 59, 38, 0.35)',
  border:       'rgba(255, 255, 255, 0.8)',
  borderFocus:  '#3E6B50',
  accent:       '#3E6B50',
  backBtnBg:    'rgba(255, 255, 255, 0.45)',
};

export function createPremiumAuthStyles(C) {
  return StyleSheet.create({
    container: { flex: 1, backgroundColor: LIGHT.bg },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: SPACING.lg,
      paddingBottom: SPACING.sm,
    },
    backBtn: {
      width: 42,
      height: 42,
      borderRadius: 21,
      backgroundColor: LIGHT.backBtnBg,
      borderWidth: 1,
      borderColor: LIGHT.border,
      alignItems: 'center',
      justifyContent: 'center',
    },
    logoBadge: {
      paddingHorizontal: SPACING.md + 2,
      paddingVertical: SPACING.xs + 2,
      backgroundColor: 'rgba(255,255,255,0.6)',
      borderRadius: RADIUS.full,
      borderWidth: 1,
      borderColor: LIGHT.border,
    },
    logoBadgeText: { ...FONT.label, color: '#0D3B26', fontWeight: '800', letterSpacing: 1.5, fontSize: 11 },
    scroll: {
      paddingHorizontal: SPACING.lg,
      paddingTop: SPACING.md,
      paddingBottom: 40,
    },
    title: { ...FONT.h1, color: LIGHT.text, marginBottom: 4, fontSize: 30, fontWeight: '800' },
    subtitle: { ...FONT.body, color: LIGHT.textMuted, marginBottom: SPACING.lg, fontSize: 15 },
    errorBanner: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: SPACING.sm,
      backgroundColor: 'rgba(254,226,226,0.92)',
      borderRadius: RADIUS.lg,
      padding: SPACING.md,
      marginBottom: SPACING.lg,
      borderWidth: 1,
      borderColor: 'rgba(220,80,80,0.2)',
    },
    errorText: { ...FONT.bodySmall, color: C.error, flex: 1 },
    // ── THE GLASS FORM CARD ──────────────────────────────────
    form: { 
      gap: SPACING.md + 4, 
      marginBottom: SPACING.lg,
      backgroundColor: 'rgba(255,255,255,0.25)',
      paddingHorizontal: SPACING.lg,
      paddingTop: SPACING.xl,
      paddingBottom: SPACING.xl,
      borderRadius: 20,
      borderWidth: 1.5,
      borderColor: 'rgba(255,255,255,0.7)',
      overflow: 'hidden', // Ensures BlurView clips to borderRadius
      // Specular highlight effect via shadow
      shadowColor: '#FFFFFF',
      shadowOffset: { width: 0, height: -1 },
      shadowOpacity: 0.5,
      shadowRadius: 0,
      elevation: 8,
      // New sizing for smaller card
      width: '90%',
      maxWidth: 340,
      alignSelf: 'center',
    },
    field: { gap: 6 },
    label: { ...FONT.label, color: LIGHT.text, fontWeight: '700', fontSize: 13, letterSpacing: 0.3 },
    labelRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
    forgotText: { ...FONT.bodySmallMedium, color: LIGHT.accent, fontWeight: '700', fontSize: 12 },
    inputWrap: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: 'rgba(255,255,255,0.6)',
      borderRadius: 16,
      borderWidth: 1,
      borderColor: 'rgba(255,255,255,0.85)',
      paddingHorizontal: SPACING.md,
      height: 52,
    },
    inputWrapFocused: {
      borderColor: LIGHT.borderFocus,
      borderWidth: 1.5,
      backgroundColor: 'rgba(255,255,255,0.9)',
      shadowColor: LIGHT.borderFocus,
      shadowOffset: { width: 0, height: 0 },
      shadowOpacity: 0.15,
      shadowRadius: 8,
    },
    inputWrapError: {
      borderColor: C.error,
      borderWidth: 1.5,
    },
    fieldError: { ...FONT.caption, color: C.error, marginTop: 2 },
    inputIcon: { marginRight: SPACING.sm },
    input: {
      flex: 1,
      fontSize: 15,
      fontWeight: '500',
      color: LIGHT.text,
      textAlignVertical: 'center',
      paddingVertical: 0,
    },
    eyeBtn: { padding: SPACING.xs },
    // ── CTA BUTTON ───────────────────────────────────────────
    primaryBtn: {
      borderRadius: RADIUS.full,
      overflow: 'hidden',
      marginTop: SPACING.sm,
      shadowColor: '#3E6B50',
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.35,
      shadowRadius: 16,
      elevation: 8,
    },
    primaryBtnDisabled: { opacity: 0.5 },
    primaryBtnGradient: { height: 56, alignItems: 'center', justifyContent: 'center' },
    primaryBtnText: { ...FONT.h5, color: '#FFFFFF', fontWeight: '800', fontSize: 17, letterSpacing: 0.3 },
    // ── DIVIDER & SOCIAL ────────────────────────────────────
    divider: { flexDirection: 'row', alignItems: 'center', gap: SPACING.md, marginBottom: SPACING.md },
    dividerLine: { flex: 1, height: StyleSheet.hairlineWidth, backgroundColor: 'rgba(13,59,38,0.2)' },
    dividerText: { ...FONT.caption, color: LIGHT.textMuted, textTransform: 'uppercase', letterSpacing: 1, fontSize: 10 },
    social: { flexDirection: 'row', justifyContent: 'center', gap: SPACING.md, marginBottom: SPACING.xl },
    socialBtn: {
      width: 54,
      height: 54,
      borderRadius: 27,
      backgroundColor: 'rgba(255,255,255,0.55)',
      borderWidth: 1,
      borderColor: 'rgba(255,255,255,0.8)',
      alignItems: 'center',
      justifyContent: 'center',
    },
    socialBtnLabel: { ...FONT.h4, color: LIGHT.text, fontWeight: '700' },
    // ── FOOTER ──────────────────────────────────────────────
    footer: { alignItems: 'center', marginTop: SPACING.md },
    footerText: { ...FONT.body, color: LIGHT.textMuted, fontSize: 14 },
    footerLink: { color: LIGHT.accent, fontWeight: '800' },
    // ── PASSWORD STRENGTH ───────────────────────────────────
    strength: { flexDirection: 'row', alignItems: 'center', gap: SPACING.sm, marginTop: 4 },
    strengthBar: { flex: 1, flexDirection: 'row', gap: 3 },
    strengthSegment: { flex: 1, height: 4, borderRadius: 2 },
    strengthLabel: { ...FONT.captionMedium, fontSize: 11 },
    // ── CHECKBOX / AGREE ────────────────────────────────────
    agreeRow: { flexDirection: 'row', alignItems: 'flex-start', gap: SPACING.sm, marginTop: SPACING.xs },
    checkbox: {
      width: 22,
      height: 22,
      borderRadius: 6,
      borderWidth: 1.5,
      borderColor: 'rgba(62,107,80, 0.4)',
      alignItems: 'center',
      justifyContent: 'center',
      marginTop: 1,
      backgroundColor: 'rgba(255,255,255,0.5)',
    },
    checkboxActive: { backgroundColor: LIGHT.accent, borderColor: LIGHT.accent },
    agreeText: { ...FONT.bodySmall, color: LIGHT.textMuted, flex: 1, lineHeight: 20, fontSize: 12.5 },
    agreeLink: { color: LIGHT.accent, fontWeight: '700' },
  });
}

export function createPremiumForgotStyles(C) {
  return StyleSheet.create({
    container: { flex: 1, backgroundColor: LIGHT.bg },
    header: { paddingHorizontal: SPACING.lg, paddingBottom: SPACING.md },
    backBtn: {
      width: 40,
      height: 40,
      borderRadius: RADIUS.md,
      backgroundColor: LIGHT.backBtnBg,
      alignItems: 'center',
      justifyContent: 'center',
    },
    content: { flex: 1, paddingHorizontal: SPACING.xl, paddingTop: SPACING.xxl },
    iconWrap: { marginBottom: SPACING.xxl },
    icon: {
      width: 72,
      height: 72,
      borderRadius: RADIUS.xl,
      alignItems: 'center',
      justifyContent: 'center',
    },
    title: { ...FONT.h1, color: LIGHT.text, marginBottom: SPACING.sm },
    subtitle: { ...FONT.body, color: LIGHT.textMuted, lineHeight: 24, marginBottom: SPACING.xxl },
    emailHighlight: { color: LIGHT.accent, fontWeight: '600' },
    errorBanner: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: SPACING.sm,
      backgroundColor: 'rgba(254,226,226,0.9)',
      borderRadius: RADIUS.md,
      padding: SPACING.md,
      marginBottom: SPACING.lg,
    },
    errorText: { ...FONT.bodySmall, color: C.error, flex: 1 },
    field: { gap: SPACING.sm, marginBottom: SPACING.xxl },
    label: { ...FONT.label, color: LIGHT.text, fontWeight: '600' },
    inputWrap: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: LIGHT.surface,
      borderRadius: RADIUS.md,
      borderWidth: 1.5,
      borderColor: LIGHT.border,
      paddingHorizontal: SPACING.md,
      height: 52,
    },
    inputIcon: { marginRight: SPACING.sm },
    input: {
      flex: 1,
      fontSize: 15,
      fontWeight: '400',
      color: LIGHT.text,
      textAlignVertical: 'center',
      paddingVertical: 0,
    },
    sendBtn: { borderRadius: RADIUS.lg, overflow: 'hidden', marginBottom: SPACING.lg, ...SHADOWS.green },
    sendBtnGradient: { height: 54, alignItems: 'center', justifyContent: 'center' },
    sendBtnText: { ...FONT.h5, color: '#FFFFFF' },
    backToLogin: { alignItems: 'center', paddingVertical: SPACING.md },
    backToLoginText: { ...FONT.bodyMedium, color: LIGHT.accent },
    successWrap: { alignItems: 'center', paddingTop: SPACING.section },
    successIcon: {
      width: 88,
      height: 88,
      borderRadius: RADIUS.xxl,
      backgroundColor: 'rgba(62,107,80,0.12)',
      borderWidth: 1,
      borderColor: 'rgba(62,107,80,0.25)',
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: SPACING.xxl,
    },
  });
}
