// src/constants/premiumAuthStyles.js
// Light cream auth UI — warm background, clean inputs, sage green accents.

import { StyleSheet } from 'react-native';
import { FONT, SPACING, RADIUS, SHADOWS } from './theme';

const LIGHT = {
  bg:           '#F9F7F2',
  surface:      '#FFFFFF',
  text:         '#1E1E1C',
  textMuted:    '#6B6B68',
  textHint:     '#A0A0A0',
  border:       '#E4DDD2',
  borderFocus:  '#3E6B50',
  accent:       '#3E6B50',
  backBtnBg:    'rgba(30,30,28,0.06)',
};

export function createPremiumAuthStyles(C) {
  return StyleSheet.create({
    container: { flex: 1, backgroundColor: LIGHT.bg },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: SPACING.lg,
      paddingBottom: SPACING.md,
    },
    backBtn: {
      width: 40,
      height: 40,
      borderRadius: RADIUS.md,
      backgroundColor: LIGHT.backBtnBg,
      alignItems: 'center',
      justifyContent: 'center',
    },
    logoBadge: {
      paddingHorizontal: SPACING.md,
      paddingVertical: SPACING.xs,
      backgroundColor: 'rgba(62,107,80,0.1)',
      borderRadius: RADIUS.full,
      borderWidth: 1,
      borderColor: 'rgba(62,107,80,0.2)',
    },
    logoBadgeText: { ...FONT.label, color: LIGHT.accent, fontWeight: '700', letterSpacing: 1 },
    scroll: {
      paddingHorizontal: SPACING.xl,
      paddingTop: SPACING.xxl,
      paddingBottom: 40,
    },
    title: { ...FONT.h1, color: LIGHT.text, marginBottom: SPACING.xs },
    subtitle: { ...FONT.body, color: LIGHT.textMuted, marginBottom: SPACING.xxl },
    errorBanner: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: SPACING.sm,
      backgroundColor: 'rgba(254,226,226,0.9)',
      borderRadius: RADIUS.md,
      padding: SPACING.md,
      marginBottom: SPACING.lg,
      borderWidth: 1,
      borderColor: 'rgba(220,80,80,0.15)',
    },
    errorText: { ...FONT.bodySmall, color: C.error, flex: 1 },
    form: { gap: SPACING.lg, marginBottom: SPACING.xxl },
    field: { gap: SPACING.sm },
    label: { ...FONT.label, color: LIGHT.text, fontWeight: '600' },
    labelRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
    forgotText: { ...FONT.bodySmallMedium, color: LIGHT.accent, fontWeight: '600' },
    inputWrap: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: LIGHT.surface,
      borderRadius: RADIUS.xl,
      borderWidth: 1.5,
      borderColor: LIGHT.border,
      paddingHorizontal: SPACING.md,
      height: 54,
    },
    inputWrapFocused: {
      borderColor: LIGHT.borderFocus,
      borderWidth: 1.5,
    },
    inputWrapError: {
      borderColor: C.error,
      borderWidth: 1.5,
    },
    fieldError: { ...FONT.caption, color: C.error, marginTop: 4 },
    inputIcon: { marginRight: SPACING.sm },
    input: {
      flex: 1,
      fontSize: 15,
      fontWeight: '400',
      color: LIGHT.text,
      textAlignVertical: 'center',
      paddingVertical: 0,
    },
    eyeBtn: { padding: SPACING.xs },
    primaryBtn: {
      borderRadius: RADIUS.lg,
      overflow: 'hidden',
      marginBottom: SPACING.xxl,
      ...SHADOWS.green,
    },
    primaryBtnDisabled: { opacity: 0.6 },
    primaryBtnGradient: { height: 54, alignItems: 'center', justifyContent: 'center' },
    primaryBtnText: { ...FONT.h5, color: '#FFFFFF', fontWeight: '700' },
    divider: { flexDirection: 'row', alignItems: 'center', gap: SPACING.md, marginBottom: SPACING.lg },
    dividerLine: { flex: 1, height: 1, backgroundColor: LIGHT.border },
    dividerText: { ...FONT.bodySmall, color: LIGHT.textMuted },
    social: { flexDirection: 'row', justifyContent: 'center', gap: SPACING.md, marginBottom: SPACING.xxl },
    socialBtn: {
      width: 52,
      height: 52,
      borderRadius: RADIUS.md,
      backgroundColor: LIGHT.surface,
      borderWidth: 1.5,
      borderColor: LIGHT.border,
      alignItems: 'center',
      justifyContent: 'center',
    },
    socialBtnLabel: { ...FONT.h4, color: LIGHT.text },
    footer: { alignItems: 'center' },
    footerText: { ...FONT.body, color: LIGHT.textMuted },
    footerLink: { color: LIGHT.accent, fontWeight: '600' },
    strength: { flexDirection: 'row', alignItems: 'center', gap: SPACING.sm, marginTop: SPACING.xs },
    strengthBar: { flex: 1, flexDirection: 'row', gap: 4 },
    strengthSegment: { flex: 1, height: 3, borderRadius: 2 },
    strengthLabel: { ...FONT.captionMedium },
    agreeRow: { flexDirection: 'row', alignItems: 'flex-start', gap: SPACING.sm },
    checkbox: {
      width: 20,
      height: 20,
      borderRadius: RADIUS.xs,
      borderWidth: 1.5,
      borderColor: LIGHT.border,
      alignItems: 'center',
      justifyContent: 'center',
      marginTop: 1,
      backgroundColor: LIGHT.surface,
    },
    checkboxActive: { backgroundColor: LIGHT.accent, borderColor: LIGHT.accent },
    agreeText: { ...FONT.bodySmall, color: LIGHT.textMuted, flex: 1, lineHeight: 18 },
    agreeLink: { color: LIGHT.accent, fontWeight: '600' },
  });
}

export function createPremiumForgotStyles(C) {
  return StyleSheet.create({
    container: { flex: 1, backgroundColor: LIGHT.bg },
    header: { paddingHorizontal: SPACING.lg, paddingBottom: SPACING.md },
    backBtn: {
      width: 40,
      height: 40,
      borderRadius: RADIUS.md,
      backgroundColor: LIGHT.backBtnBg,
      alignItems: 'center',
      justifyContent: 'center',
    },
    content: { flex: 1, paddingHorizontal: SPACING.xl, paddingTop: SPACING.xxl },
    iconWrap: { marginBottom: SPACING.xxl },
    icon: {
      width: 72,
      height: 72,
      borderRadius: RADIUS.xl,
      alignItems: 'center',
      justifyContent: 'center',
    },
    title: { ...FONT.h1, color: LIGHT.text, marginBottom: SPACING.sm },
    subtitle: { ...FONT.body, color: LIGHT.textMuted, lineHeight: 24, marginBottom: SPACING.xxl },
    emailHighlight: { color: LIGHT.accent, fontWeight: '600' },
    errorBanner: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: SPACING.sm,
      backgroundColor: 'rgba(254,226,226,0.9)',
      borderRadius: RADIUS.md,
      padding: SPACING.md,
      marginBottom: SPACING.lg,
    },
    errorText: { ...FONT.bodySmall, color: C.error, flex: 1 },
    field: { gap: SPACING.sm, marginBottom: SPACING.xxl },
    label: { ...FONT.label, color: LIGHT.text, fontWeight: '600' },
    inputWrap: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: LIGHT.surface,
      borderRadius: RADIUS.md,
      borderWidth: 1.5,
      borderColor: LIGHT.border,
      paddingHorizontal: SPACING.md,
      height: 52,
    },
    inputIcon: { marginRight: SPACING.sm },
    input: {
      flex: 1,
      fontSize: 15,
      fontWeight: '400',
      color: LIGHT.text,
      textAlignVertical: 'center',
      paddingVertical: 0,
    },
    sendBtn: { borderRadius: RADIUS.lg, overflow: 'hidden', marginBottom: SPACING.lg, ...SHADOWS.green },
    sendBtnGradient: { height: 54, alignItems: 'center', justifyContent: 'center' },
    sendBtnText: { ...FONT.h5, color: '#FFFFFF' },
    backToLogin: { alignItems: 'center', paddingVertical: SPACING.md },
    backToLoginText: { ...FONT.bodyMedium, color: LIGHT.accent },
    successWrap: { alignItems: 'center', paddingTop: SPACING.section },
    successIcon: {
      width: 88,
      height: 88,
      borderRadius: RADIUS.xxl,
      backgroundColor: 'rgba(62,107,80,0.12)',
      borderWidth: 1,
      borderColor: 'rgba(62,107,80,0.25)',
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: SPACING.xxl,
    },
  });
}
